# Generated by Django 4.2.26 on 2025-12-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=200, null=True)),
                ('Product_code', models.CharField(max_length=200, null=True)),
                ('Price', models.FloatField(default=0)),
                ('Gst', models.IntegerField(default=0)),
            ],
        ),
    ]
