# Generated by Django 4.2.26 on 2025-12-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Food_Product',
            field=models.BooleanField(default=False),
        ),
    ]
