# Generated by Django 4.2.26 on 2026-01-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_product_food_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Gst',
            new_name='gst',
        ),
    ]
